version: '3'

tasks:
  default:
    desc: "Render all documents"
    deps: [render-index]

  render-case-studies:
    desc: "Render case studies (generates figures)"
    deps: [instantiate, install-extensions]
    cmds:
      - quarto render case-studies.qmd
    sources:
      - case-studies.qmd
    generates:
      - figures/fig-mishra.pdf
      - figures/fig-mishra.png
      - figures/fig-epinow2.pdf
      - figures/fig-epinow2.png
      - case-studies.html
      - case-studies.pdf
      - case-studies.ipynb
    status:
      - test -f case-studies.html
      - test -f case-studies.pdf
      - test -f figures/fig-mishra.pdf
      - test -f figures/fig-epinow2.pdf

  render-index:
    desc: "Render main document"
    deps: [instantiate, install-extensions, render-case-studies]
    cmds:
      - quarto render index.qmd
    sources:
      - index.qmd
      - figures/fig-mishra.pdf
      - figures/fig-epinow2.pdf
    generates:
      - index.html
      - index.pdf
      - index.ipynb
    status:
      - test -f index.html
      - test -f index.pdf

  install-julia:
    desc: "Install Julia 1.11.6 using juliaup and set as default"
    cmds:
      - juliaup add 1.11.6
      - juliaup override set 1.11.6
    status:
      - juliaup status | grep -q "1.11.6"

  instantiate:
    desc: "Activate and instantiate the Julia project environment"
    deps: [install-julia]
    cmds:
      - git submodule update --init --recursive
      - julia +1.11.6 -e "using Pkg; Pkg.activate(\".\"); Pkg.instantiate()"
    sources:
      - Project.toml
      - Manifest.toml
    generates:
      - LocalPreferences.toml

  repl:
    desc: "Launch Julia REPL with project environment active"
    deps: [instantiate]
    cmds:
      - julia +1.11.6 -i -e "using Pkg; Pkg.activate(\".\")"
    interactive: true

  install-extensions:
    desc: "Install Quarto extensions"
    cmds:
      - quarto add kapsner/authors-block --no-prompt
    status:
      - test -d _extensions/authors-block

  preview:
    desc: "Preview the Quarto document with live reload"
    deps: [instantiate, install-extensions]
    cmds:
      - quarto preview
    interactive: true

  renv-restore:
    desc: "Restore R environment from renv.lock"
    cmds:
      - Rscript -e 'renv::restore()'
    sources:
      - renv.lock
    status:
      - Rscript -e 'stopifnot(renv::status()$synchronized)'

  setup-epiawarer:
    desc: "Set up EpiAwareR R package with Julia backend"
    deps: [instantiate, renv-restore]
    cmds:
      - |
        Rscript -e '
        remotes::install_local("EpiAwareR", dependencies = FALSE, upgrade = "never")
        library(EpiAwareR)
        epiaware_setup_julia()
        '
    status:
      - Rscript -e 'library(EpiAwareR)'
