version: '3'

tasks:
  default:
    desc: "Render all documents"
    deps: [render-case-studies, render-index]

  render-case-studies:
    desc: "Render case studies (generates figures)"
    deps: [instantiate, install-extensions]
    cmds:
      - quarto render case-studies.qmd
    sources:
      - case-studies.qmd
    generates:
      - figures/fig-figure3.pdf
      - figures/fig-figure3.png
      - figures/fig-figure4.pdf
      - figures/fig-figure4.png
      - case-studies.html
      - case-studies.pdf
    status:
      - test -f case-studies.html
      - test -f case-studies.pdf
      - test -f figures/fig-figure3.pdf
      - test -f figures/fig-figure4.pdf

  render-index:
    desc: "Render main document"
    deps: [instantiate, install-extensions, render-case-studies]
    cmds:
      - quarto render index.qmd
    sources:
      - index.qmd
      - figures/fig-figure3.pdf
      - figures/fig-figure4.pdf
    generates:
      - index.html
      - index.pdf
    status:
      - test -f index.html
      - test -f index.pdf

  install-julia:
    desc: "Install Julia 1.11.6 using juliaup and set as default"
    cmds:
      - juliaup add 1.11.6
      - juliaup override set 1.11.6
    status:
      - juliaup status | grep -q "1.11.6"

  instantiate:
    desc: "Activate and instantiate the Julia project environment"
    deps: [install-julia]
    cmds:
      - git submodule update --init --recursive
      - julia +1.11.6 -e "using Pkg; Pkg.activate(\".\"); Pkg.instantiate()"
    sources:
      - Project.toml
      - Manifest.toml
    generates:
      - LocalPreferences.toml

  repl:
    desc: "Launch Julia REPL with project environment active"
    deps: [instantiate]
    cmds:
      - julia +1.11.6 -i -e "using Pkg; Pkg.activate(\".\")"
    interactive: true

  install-extensions:
    desc: "Install Quarto extensions"
    cmds:
      - quarto add kapsner/authors-block --no-prompt
    status:
      - test -d _extensions/authors-block

  preview:
    desc: "Preview the Quarto document with live reload"
    deps: [instantiate, install-extensions]
    cmds:
      - quarto preview
    interactive: true
